# Generated by build/generate-r8-rules.sh from dd-sdk-android-okhttp 3.12.1. Do not edit by hand.
#
# Consumer rules for R8/ProGuard, attached to consuming applications by
# DatadogNet.OkHttp.Android.targets. Two sections: upstream's own consumer rules, recovered
# from the .aar because .NET for Android never feeds an embedded proguard.txt to R8, and
# curated keeps for the entry surface C# reaches through JNI alone - reflection a Java
# shrinker cannot see, so without them a shrunk Release build removes classes and the
# binding fails at runtime with ClassNotFoundException.

# ---- Upstream consumer rules, verbatim from dd-sdk-android-okhttp-3.12.1.aar!proguard.txt ----
# (none: dd-sdk-android-okhttp 3.12.1 embeds no proguard.txt)

# ---- Curated keeps for the JNI-only entry surface ----
# The interceptors and the event-listener factory are constructed by the app and handed to an
# OkHttpClient.Builder; nothing on the Java side ever news them up.
-keep class com.datadog.android.okhttp.DatadogInterceptor { *; }
-keep class com.datadog.android.okhttp.DatadogInterceptor$* { *; }
-keep class com.datadog.android.okhttp.DatadogEventListener { *; }
-keep class com.datadog.android.okhttp.DatadogEventListener$* { *; }
-keep class com.datadog.android.okhttp.trace.TracingInterceptor { *; }
-keep class com.datadog.android.okhttp.trace.TracingInterceptor$* { *; }
