# Generated by build/generate-r8-rules.sh from dd-sdk-android-webview 3.12.1. Do not edit by hand.
#
# Consumer rules for R8/ProGuard, attached to consuming applications by
# DatadogNet.WebView.Android.targets. Two sections: upstream's own consumer rules, recovered
# from the .aar because .NET for Android never feeds an embedded proguard.txt to R8, and
# curated keeps for the entry surface C# reaches through JNI alone - reflection a Java
# shrinker cannot see, so without them a shrunk Release build removes classes and the
# binding fails at runtime with ClassNotFoundException.

# ---- Upstream consumer rules, verbatim from dd-sdk-android-webview-3.12.1.aar!proguard.txt ----
# (none: dd-sdk-android-webview 3.12.1 embeds no proguard.txt)

# ---- Curated keeps for the JNI-only entry surface ----
# WebViewTracking is called from .NET through JNI only, which a Java shrinker cannot see, so
# without these it is removed from shrunk Release builds and Enable throws ClassNotFoundException
# at runtime. Keeping the entry type and its nested types is enough: everything they use survives
# through ordinary reference reachability from there.
-keep class com.datadog.android.webview.WebViewTracking { *; }
-keep class com.datadog.android.webview.WebViewTracking$* { *; }
