# Generated by build/generate-r8-rules.sh from dd-sdk-android-trace-internal 3.12.1. Do not edit by hand.
#
# Consumer rules for R8/ProGuard, attached to consuming applications by
# DatadogNet.TraceInternal.Android.targets. Two sections: upstream's own consumer rules, recovered
# from the .aar because .NET for Android never feeds an embedded proguard.txt to R8, and
# curated keeps for the entry surface C# reaches through JNI alone - reflection a Java
# shrinker cannot see, so without them a shrunk Release build removes classes and the
# binding fails at runtime with ClassNotFoundException.

# ---- Upstream consumer rules, verbatim from dd-sdk-android-trace-internal-3.12.1.aar!proguard.txt ----
# (none: dd-sdk-android-trace-internal 3.12.1 embeds no proguard.txt)

# ---- Curated keeps for the JNI-only entry surface ----
# (none) This module is the vendored dd-trace-java engine under com.datadog.trace.**; nothing in
# it is called from C# - the package ships the .aar without binding it - and its classes survive
# through reachability from dd-sdk-android-trace's kept entry points, which construct the engine.
