# Generated by build/generate-r8-rules.sh from dd-sdk-android-trace 3.12.1. Do not edit by hand.
#
# Consumer rules for R8/ProGuard, attached to consuming applications by
# DatadogNet.Trace.Android.targets. Two sections: upstream's own consumer rules, recovered
# from the .aar because .NET for Android never feeds an embedded proguard.txt to R8, and
# curated keeps for the entry surface C# reaches through JNI alone - reflection a Java
# shrinker cannot see, so without them a shrunk Release build removes classes and the
# binding fails at runtime with ClassNotFoundException.

# ---- Upstream consumer rules, verbatim from dd-sdk-android-trace-3.12.1.aar!proguard.txt ----
-keep class com.datadog.android.trace.GlobalDatadogTracer {
    public com.datadog.android.trace.api.tracer.DatadogTracer getOrNull();
    public static com.datadog.android.trace.GlobalDatadogTracer INSTANCE;
}
-keepclassmembernames class org.jctools.** { *; }

# ---- Curated keeps for the JNI-only entry surface ----
-keep class com.datadog.android.trace.Trace { *; }
-keep class com.datadog.android.trace.TraceConfiguration { *; }
-keep class com.datadog.android.trace.TraceConfiguration$* { *; }
-keep class com.datadog.android.trace.DatadogTracing { *; }
-keep class com.datadog.android.trace.GlobalDatadogTracer { *; }
