# Generated by build/generate-r8-rules.sh from dd-sdk-android-internal 3.12.1. Do not edit by hand.
#
# Consumer rules for R8/ProGuard, attached to consuming applications by
# DatadogNet.Internal.Android.targets. Two sections: upstream's own consumer rules, recovered
# from the .aar because .NET for Android never feeds an embedded proguard.txt to R8, and
# curated keeps for the entry surface C# reaches through JNI alone - reflection a Java
# shrinker cannot see, so without them a shrunk Release build removes classes and the
# binding fails at runtime with ClassNotFoundException.

# ---- Upstream consumer rules, verbatim from dd-sdk-android-internal-3.12.1.aar!proguard.txt ----
# (none: dd-sdk-android-internal 3.12.1 embeds no proguard.txt)

# ---- Curated keeps for the JNI-only entry surface ----
# dd-sdk-android-internal has no C#-facing entry point of its own - it is the foundation the
# other modules call from Kotlin, and their keeps carry it. EvictingQueue is pinned anyway: the
# device tests resolve it by name as proof this module's .aar reached the app, and nothing else
# guarantees a shrinker keeps any recognisable class of it alive.
-keep class com.datadog.android.internal.collections.EvictingQueue { *; }
