# Generated by build/generate-r8-rules.sh from dd-sdk-android-session-replay-compose 3.12.1. Do not edit by hand.
#
# Consumer rules for R8/ProGuard, attached to consuming applications by
# DatadogNet.SessionReplayCompose.Android.targets. Two sections: upstream's own consumer rules, recovered
# from the .aar because .NET for Android never feeds an embedded proguard.txt to R8, and
# curated keeps for the entry surface C# reaches through JNI alone - reflection a Java
# shrinker cannot see, so without them a shrunk Release build removes classes and the
# binding fails at runtime with ClassNotFoundException.

# ---- Upstream consumer rules, verbatim from dd-sdk-android-session-replay-compose-3.12.1.aar!proguard.txt ----
# Keep the Compose internals class name. We need this in the SR recorder.
-keepnames class androidx.compose.runtime.Composition
-keepnames class androidx.compose.ui.platform.ComposeView
-keepnames class androidx.compose.material.DefaultButtonColors
-keep class androidx.compose.ui.platform.WrappedComposition {
    <fields>;
}
-keepclassmembers class androidx.compose.ui.platform.AbstractComposeView {
    <fields>;
}
-keepclassmembers class androidx.compose.ui.platform.AndroidComposeView {
     <fields>;
}
-keepclassmembers class androidx.compose.foundation.text.modifiers.TextStringSimpleElement {
     <fields>;
}
-keep class androidx.compose.material.CheckDrawingCache {
     <fields>;
}
-keep class androidx.compose.material.CheckboxKt$CheckboxImpl$1$1 {
     <fields>;
}
-keep class androidx.compose.material.RadioButtonKt$RadioButton$2$1 {
     <fields>;
}
-keep class androidx.compose.ui.draw.DrawBehindElement {
     <fields>;
}
-keepclassmembers class androidx.compose.foundation.BackgroundElement {
     <fields>;
}
-keep class androidx.compose.ui.node.LayoutNode {
     *;
}
-keep class androidx.compose.ui.node.NodeChain {
    <fields>;
}
-keep class androidx.compose.ui.Modifier$Node{
    <fields>;
}
-keep class coil3.compose.internal.ContentPainterNode{
    <fields>;
}
-keep class coil3.compose.AsyncImagePainter{
    <methods>;
}

-keep class androidx.compose.ui.semantics.SemanticsNode {
     <fields>;
}
-keep class androidx.compose.ui.draw.PainterElement {
     <fields>;
}
-keep class androidx.compose.ui.graphics.vector.VectorPainter {
     <fields>;
}
-keep class androidx.compose.ui.graphics.painter.BitmapPainter {
     <fields>;
}
-keep class androidx.compose.ui.graphics.vector.VectorComponent {
     <fields>;
}
-keep class androidx.compose.ui.graphics.vector.DrawCache {
     <fields>;
}
-keep class androidx.compose.ui.graphics.AndroidImageBitmap {
     <fields>;
}
-keep class coil.compose.ContentPainterElement {
     <fields>;
}
-keep class coil.compose.ContentPainterModifier {
     <fields>;
}
-keep class coil.compose.AsyncImagePainter {
     <fields>;
}
-keep class androidx.compose.foundation.layout.PaddingElement{
    <fields>;
}
-keep class androidx.compose.ui.graphics.GraphicsLayerElement{
    <fields>;
}
-keep class androidx.compose.ui.text.ParagraphInfo{
    <fields>;
}
-keep class androidx.compose.ui.text.AndroidParagraph{
    <fields>;
}
-keep class androidx.compose.ui.text.android.TextLayout{
    <fields>;
}

# ---- Curated keeps for the JNI-only entry surface ----
# Constructed by the app for SessionReplayConfiguration.Builder.addExtensionSupport and by
# nothing on the Java side; the mappers it registers survive through it.
-keep class com.datadog.android.sessionreplay.compose.ComposeExtensionSupport { *; }
