# Generated by build/generate-r8-rules.sh from dd-sdk-android-core 3.12.1. Do not edit by hand.
#
# Consumer rules for R8/ProGuard, attached to consuming applications by
# DatadogNet.Core.Android.targets. Two sections: upstream's own consumer rules, recovered
# from the .aar because .NET for Android never feeds an embedded proguard.txt to R8, and
# curated keeps for the entry surface C# reaches through JNI alone - reflection a Java
# shrinker cannot see, so without them a shrunk Release build removes classes and the
# binding fails at runtime with ClassNotFoundException.

# ---- Upstream consumer rules, verbatim from dd-sdk-android-core-3.12.1.aar!proguard.txt ----
# see https://github.com/DataDog/dd-sdk-android/issues/3491 for motivation
# we are using Work Manager version which is not compatible with R8 full mode
-keep class androidx.work.impl.WorkDatabase_Impl { <init>(); }

# ---- Curated keeps for the JNI-only entry surface ----
# The SDK's front door: everything an app touches before and around Datadog.initialize.
-keep class com.datadog.android.Datadog { *; }
-keep class com.datadog.android.DatadogSite { *; }
-keep class com.datadog.android.privacy.TrackingConsent { *; }
-keep class com.datadog.android.core.configuration.Configuration { *; }
-keep class com.datadog.android.core.configuration.Configuration$* { *; }
-keep class com.datadog.android.core.configuration.BatchSize { *; }
-keep class com.datadog.android.core.configuration.UploadFrequency { *; }
