# Generated by build/generate-r8-rules.sh from dd-sdk-android-trace-api 3.12.1. Do not edit by hand.
#
# Consumer rules for R8/ProGuard, attached to consuming applications by
# DatadogNet.TraceApi.Android.targets. Two sections: upstream's own consumer rules, recovered
# from the .aar because .NET for Android never feeds an embedded proguard.txt to R8, and
# curated keeps for the entry surface C# reaches through JNI alone - reflection a Java
# shrinker cannot see, so without them a shrunk Release build removes classes and the
# binding fails at runtime with ClassNotFoundException.

# ---- Upstream consumer rules, verbatim from dd-sdk-android-trace-api-3.12.1.aar!proguard.txt ----
# (none: dd-sdk-android-trace-api 3.12.1 embeds no proguard.txt)

# ---- Curated keeps for the JNI-only entry surface ----
# All interfaces: C# holds the tracer, span, scope and propagation objects the trace module
# hands out and invokes their members through JNI, so the interface methods must survive - a
# kept interface method is what keeps its implementation alive on the concrete classes.
-keep class com.datadog.android.trace.api.tracer.DatadogTracer { *; }
-keep class com.datadog.android.trace.api.tracer.DatadogTracer$* { *; }
-keep class com.datadog.android.trace.api.tracer.DatadogTracerBuilder { *; }
-keep class com.datadog.android.trace.api.span.DatadogSpan { *; }
-keep class com.datadog.android.trace.api.span.DatadogSpanBuilder { *; }
-keep class com.datadog.android.trace.api.span.DatadogSpanContext { *; }
-keep class com.datadog.android.trace.api.scope.DatadogScope { *; }
-keep class com.datadog.android.trace.api.propagation.DatadogPropagation { *; }
-keep class com.datadog.android.trace.api.trace.DatadogTraceId { *; }
-keep class com.datadog.android.trace.api.trace.DatadogTraceId$* { *; }
