# Generated by build/generate-r8-rules.sh from dd-sdk-android-logs 3.12.1. Do not edit by hand.
#
# Consumer rules for R8/ProGuard, attached to consuming applications by
# DatadogNet.Logs.Android.targets. Two sections: upstream's own consumer rules, recovered
# from the .aar because .NET for Android never feeds an embedded proguard.txt to R8, and
# curated keeps for the entry surface C# reaches through JNI alone - reflection a Java
# shrinker cannot see, so without them a shrunk Release build removes classes and the
# binding fails at runtime with ClassNotFoundException.

# ---- Upstream consumer rules, verbatim from dd-sdk-android-logs-3.12.1.aar!proguard.txt ----
# This is needed for the Datadog Error Tracking feature to work reliably,
 # this file is used by Logs and RUM modules
-keepattributes SourceFile,LineNumberTable

# ---- Curated keeps for the JNI-only entry surface ----
-keep class com.datadog.android.log.Logs { *; }
-keep class com.datadog.android.log.LogsConfiguration { *; }
-keep class com.datadog.android.log.LogsConfiguration$* { *; }
-keep class com.datadog.android.log.Logger { *; }
-keep class com.datadog.android.log.Logger$* { *; }
