# Generated by build/generate-r8-rules.sh from dd-sdk-android-rum 3.12.1. Do not edit by hand.
#
# Consumer rules for R8/ProGuard, attached to consuming applications by
# DatadogNet.RUM.Android.targets. Two sections: upstream's own consumer rules, recovered
# from the .aar because .NET for Android never feeds an embedded proguard.txt to R8, and
# curated keeps for the entry surface C# reaches through JNI alone - reflection a Java
# shrinker cannot see, so without them a shrunk Release build removes classes and the
# binding fails at runtime with ClassNotFoundException.

# ---- Upstream consumer rules, verbatim from dd-sdk-android-rum-3.12.1.aar!proguard.txt ----
# This is needed for the Datadog Error Tracking feature to work reliably,
 # this file is used by Logs and RUM modules
-keepattributes SourceFile,LineNumberTable

# Kept for our internal telemetry
-keepnames class com.datadog.android.rum.internal.monitor.DatadogRumMonitor
-keepnames class com.datadog.android.rum.internal.domain.scope.RumRawEvent
-keepnames class * extends com.datadog.android.rum.internal.domain.scope.RumRawEvent

# ---- Curated keeps for the JNI-only entry surface ----
# RumMonitor is the interface behind GlobalRumMonitor.get(); C# drives every view, action,
# resource and error through it. The view-tracking strategies are constructed by the app in
# RumConfiguration.Builder.useViewTrackingStrategy and by nothing on the Java side.
-keep class com.datadog.android.rum.Rum { *; }
-keep class com.datadog.android.rum.GlobalRumMonitor { *; }
-keep class com.datadog.android.rum.RumMonitor { *; }
-keep class com.datadog.android.rum.RumMonitor$* { *; }
-keep class com.datadog.android.rum.RumConfiguration { *; }
-keep class com.datadog.android.rum.RumConfiguration$* { *; }
-keep class com.datadog.android.rum.RumActionType { *; }
-keep class com.datadog.android.rum.RumErrorSource { *; }
-keep class com.datadog.android.rum.RumResourceKind { *; }
-keep class com.datadog.android.rum.RumResourceMethod { *; }
-keep class com.datadog.android.rum.tracking.ActivityViewTrackingStrategy { *; }
-keep class com.datadog.android.rum.tracking.FragmentViewTrackingStrategy { *; }
-keep class com.datadog.android.rum.tracking.MixedViewTrackingStrategy { *; }
-keep class com.datadog.android.rum.tracking.NavigationViewTrackingStrategy { *; }
