# Generated by build/generate-r8-rules.sh from dd-sdk-android-session-replay 3.12.1. Do not edit by hand.
#
# Consumer rules for R8/ProGuard, attached to consuming applications by
# DatadogNet.SessionReplay.Android.targets. Two sections: upstream's own consumer rules, recovered
# from the .aar because .NET for Android never feeds an embedded proguard.txt to R8, and
# curated keeps for the entry surface C# reaches through JNI alone - reflection a Java
# shrinker cannot see, so without them a shrunk Release build removes classes and the
# binding fails at runtime with ClassNotFoundException.

# ---- Upstream consumer rules, verbatim from dd-sdk-android-session-replay-3.12.1.aar!proguard.txt ----
# Keep the optional selector class name. We need this in the SR recorder.
-keepnames class * extends android.view.View
-keepnames class * extends android.graphics.drawable.Drawable
-keepnames class * extends android.graphics.ColorFilter

# Kept for our internal telemetry
-keepnames class com.datadog.android.sessionreplay.internal.recorder.listener.WindowsOnDrawListener
-keepnames class com.datadog.android.sessionreplay.internal.recorder.TreeViewTraversal
-keepnames class * extends com.datadog.android.sessionreplay.recorder.mapper.WireframeMapper
-keepnames class * extends com.datadog.android.sessionreplay.internal.async.RecordedDataQueueItem

# Keep the fine grained masking level enums
-keepnames enum * extends com.datadog.android.sessionreplay.PrivacyLevel { *; }

# ---- Curated keeps for the JNI-only entry surface ----
# The privacy types are enums whose constants C# reads as static fields while building the
# configuration; a class kept only through a method signature loses them.
-keep class com.datadog.android.sessionreplay.SessionReplay { *; }
-keep class com.datadog.android.sessionreplay.SessionReplayConfiguration { *; }
-keep class com.datadog.android.sessionreplay.SessionReplayConfiguration$* { *; }
-keep class com.datadog.android.sessionreplay.SystemRequirementsConfiguration { *; }
-keep class com.datadog.android.sessionreplay.SystemRequirementsConfiguration$* { *; }
-keep class com.datadog.android.sessionreplay.SessionReplayPrivacy { *; }
-keep class com.datadog.android.sessionreplay.TextAndInputPrivacy { *; }
-keep class com.datadog.android.sessionreplay.ImagePrivacy { *; }
-keep class com.datadog.android.sessionreplay.TouchPrivacy { *; }
