# Generated by build/generate-r8-rules.sh from dd-sdk-android-session-replay-material 3.12.1. Do not edit by hand.
#
# Consumer rules for R8/ProGuard, attached to consuming applications by
# DatadogNet.SessionReplayMaterial.Android.targets. Two sections: upstream's own consumer rules, recovered
# from the .aar because .NET for Android never feeds an embedded proguard.txt to R8, and
# curated keeps for the entry surface C# reaches through JNI alone - reflection a Java
# shrinker cannot see, so without them a shrunk Release build removes classes and the
# binding fails at runtime with ClassNotFoundException.

# ---- Upstream consumer rules, verbatim from dd-sdk-android-session-replay-material-3.12.1.aar!proguard.txt ----
# Keep the optional selector class name. We need this in the SR recorder.
-keepnames class com.google.android.material.timepicker.TimePickerView
-keepnames class com.google.android.material.datepicker.MaterialCalendarGridView

# ---- Curated keeps for the JNI-only entry surface ----
# Constructed by the app for SessionReplayConfiguration.Builder.addExtensionSupport and by
# nothing on the Java side; the mappers it registers survive through it.
-keep class com.datadog.android.sessionreplay.material.MaterialExtensionSupport { *; }
